name: Laravel CI and Deployment

on:
  push:
    branches:
      - main  # Change this to the appropriate branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up PHP
      run: |
        sudo apt update
        sudo apt upgrade -y
        sudo apt install -y curl php-cli php-mbstring git unzip

    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        php -r "unlink('composer-setup.php');"

    - name: Install Laravel Installer
      run: |
        composer global require laravel/installer
        echo 'export PATH="$PATH:$HOME/.composer/vendor/bin"' >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Create and Set Up Laravel Project
      run: |
        mkdir my-laravel-app
        cd my-laravel-app
        composer create-project --prefer-dist laravel/laravel .
        php artisan key:generate

    - name: Install Composer Dependencies
      run: |
        export COMPOSER_ALLOW_SUPERUSER=1
        cd my-laravel-app  # Change directory to your Laravel project
        composer install --no-interaction --no-dev

    # - name: Run Tests
    #  run: |
    #   cd my-laravel-app  # Change directory to your Laravel project
    #    php artisan test

    - name: Deploy to Ubuntu Server
  env:
    SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  run: |
    mkdir -p /home/runner/.ssh/
    echo "$SSH_PRIVATE_KEY" > /home/runner/.ssh/id_rsa
    chmod 600 /home/runner/.ssh/id_rsa

    # Replace `172.31.32.134` with your server's IP address
    ssh ubuntu@172.31.39.209 'cd /home/ubuntu/my-laravel-app && git pull && composer install && php artisan migrate'
