name: Laravel CI and Deployment

on:
  push:
    branches:
      - main # Change this to the appropriate branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up PHP
      run: |
        sudo apt update
        sudo apt upgrade -y
        sudo apt install -y curl php-cli php-mbstring git unzip

    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        php -r "unlink('composer-setup.php');"

    - name: Install Laravel Installer
      run: |
        composer global require laravel/installer
        echo 'export PATH="$PATH:$HOME/.composer/vendor/bin"' >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Create and Set Up Laravel Project
      run: |
        mkdir my-laravel-app
        cd my-laravel-app
        composer create-project --prefer-dist laravel/laravel .
        php artisan key:generate --force

    - name: Install Composer Dependencies
      run: |
        export COMPOSER_ALLOW_SUPERUSER=1
        cd my-laravel-app # Change directory to your Laravel project
        composer install --no-interaction --no-dev

    # Uncomment the next steps if you want to run tests
    # - name: Run Tests
    #   run: |
    #     cd my-laravel-app # Change directory to your Laravel project
    #     php artisan test

    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bash -s' << 'EOF'
          cd my-laravel-app
          git pull
          composer install --no-interaction --no-dev
          php artisan migrate
          sudo apt update
          sudo apt upgrade -y
        EOF
